const FEEDBACK_COLLECTION = 'feedback';
const GEAR_COLLECTION = 'gear';
const RECRUITMENT_COLLECTION = 'recruitment';

module.exports = {
  FEEDBACK_COLLECTION,
  GEAR_COLLECTION,
  RECRUITMENT_COLLECTION
};
